grpc:
  client:
    report-service:
      address: 'static://localhost:9090' # Порт основного приложения
      negotiation-type: plaintext

telegram:
  bot:
    username: HseKpoBot
    token: 7668683034:AAHSxhMeXGgDROKrqI7ZrFpS7rye_NZMzzw
    chat-id: "806256256"