services:
  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: hsepassword
      POSTGRES_DB: car_db
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '6431:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d car_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

#  app:
#    build: .
#    container_name: car_app
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    ports:
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy