spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs/gateway
  swagger-ui:
    # path: /swagger-ui/gateway
    urls:
      - url: /v3/api-docs/gateway
        name: gateway
      - url: /v3/api-docs/storage
        name: storage
      - url: /v3/api-docs/analysis
        name: analysis
server:
  port: 8080