spring:
  application:
    name: file-storage
  datasource:
    url: jdbc:postgresql://localhost:5432/file_db
    #url: { $POSTGRESQL_URL }
    #username: { $POSTGRESQL_USERNAME }
    #password: { $POSTGRESQL_PASSWORD }
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8082